# loud or quiet?
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# modes
setw -g clock-mode-colour colour5
setw -g mode-style 'fg=colour1 bg=colour18 bold'

# panes
set -g pane-border-style 'fg=colour19 bg=colour0'
set -g pane-active-border-style 'bg=colour0 fg=colour9'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'bg=colour18 fg=colour137 dim'
set -g status-interval 5
set -g status-left '#[fg=colour15,bg=colour19,bold] #S '
set -g status-right '#[fg=colour255,bg=colour18] #(echo "#{pane_current_path}" | sed "s|^$HOME|~|")#[fg=colour220,bg=colour18]#(~/.tmux/scripts/branch.sh "#{pane_current_path}") #[fg=colour245,bg=colour18] #(~/.tmux/scripts/cpu_mem.sh) #[fg=colour233,bg=colour19] %d/%m #[fg=colour233,bg=colour8] %H:%M:%S '
set -g status-right-length 250
set -g status-left-length 40

setw -g window-status-current-style 'fg=colour1 bg=colour19 bold'
setw -g window-status-current-format ' #I#[fg=colour249]:#[fg=colour255]#W#[fg=colour249]#F '

setw -g window-status-style 'fg=colour9 bg=colour18'
setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

setw -g window-status-bell-style 'fg=colour255 bg=colour1 bold'

# messages
set -g message-style 'fg=colour232 bg=colour16 bold'

# lots of color support
set  -g default-terminal "screen-256color"
set -as terminal-features ',screen-256color:RGB'
set -ag terminal-overrides ',screen-256color:Tc'
set -ag terminal-overrides ',xterm-256color:RGB'

# Nvim stuff
set-option  -g focus-events on
set-option -sg escape-time 300

# Reload config
bind r source-file ~/.tmux.conf \; display "reloaded"
